/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Revsoft_Wabbitemu_CalcInterface */

#ifndef _Included_com_Revsoft_Wabbitemu_CalcInterface
#define _Included_com_Revsoft_Wabbitemu_CalcInterface
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    SetCacheDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_Initialize
		(JNIEnv *env, jclass classObj, jstring filePath);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    LoadFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_LoadFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    SaveCalcState
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jboolean JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_SaveCalcState
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    CreateRom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_CreateRom
  (JNIEnv *, jclass, jstring, jstring, jstring, jint);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    ResetCalc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_ResetCalc
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    RunCalcs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_RunCalcs
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    PauseCalc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_PauseCalc
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    UnpauseCalc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_UnpauseCalc
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    GetModel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_GetModel
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    Tstates
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_Tstates
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    SetSpeedCalc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_SetSpeedCalc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    PressKey
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_PressKey
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    ReleaseKey
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_ReleaseKey
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    SetAutoTurnOn
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_SetAutoTurnOn
  (JNIEnv *env, jclass classObj, jboolean turnOn);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    IsLCDActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_IsLCDActive
  (JNIEnv *, jclass);

/*
 * Class:     com_Revsoft_Wabbitemu_CalcInterface
 * Method:    GetLCD
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_Revsoft_Wabbitemu_calc_CalcInterface_GetLCD
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
